language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

os:
  - linux

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable=1' >> /etc/hhvm/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable_cli=1' >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer install -o --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors
  - vendor/bin/phpcs --standard=psr2 -np src tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

