language: php
sudo: false

php:
  - 5.5
  - 5.6
  - hhvm

os:
  - linux
  - osx

before_script:
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer install --dev -o --prefer-source

script:
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose
  - php -d zend.enable_gc=0 vendor/bin/phpcs --standard=psr2 src

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

